yolo_model:

  config_file:
    name: yolov3_endale1.cfg  #modify this 
  weight_file:
    name: yolov3_final1_endale.weights  #modify this
  threshold:
    value: 0.05
  detection_classes:
    names:
      - window


