yolo_model:

  config_file:
    name: yolov3_endale1.cfg  #modify this 
  weight_file:
    name: yolov3_final1_endale.weights  #modify this
  threshold:
    value: 0.3
  detection_classes:
    names:
      - fan    #modfiy
      - landing pad
      - net
      - pipe
      - pole
      - window
      - tree
      - wall

