yolo_model:

  config_file:
    name: yolov3_Endale.cfg  #modify this 
  weight_file:
    name: yolov3_final_endale.weights  #modify this
  threshold:
    value: 0.3
  detection_classes:
    names:
      - window    #modfiy
      - tree
