yolo_model:

  config_file:
    name: yolov3-tiny.cfg  #yolov3_endale1.cfg  #modify this 
  weight_file:
    name: yolov3-tiny_final.weights #yolov3_final1_endale.weights  #modify this
  threshold:
    value: 0.2
  detection_classes:
    names:
      - window


